// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Blue': string;
  'Green': string;
  'Legend': string;
}
export const cssExports: CssExports;
export default cssExports;
