// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Changed': string;
  'Clear': string;
  'Left': string;
  'List': string;
  'Paragraph': string;
  'Right': string;
}
export const cssExports: CssExports;
export default cssExports;
