// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Actual': string;
  'Header': string;
  'Left': string;
  'Right': string;
}
export const cssExports: CssExports;
export default cssExports;
