// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Bar': string;
  'Scroll': string;
}
export const cssExports: CssExports;
export default cssExports;
